/*
* ============================================================================
*  Name     : CAuebTrilizaView from AuebTrilizaView.h
*  Part of  : AuebTriliza
*  Created  : 11/12/2004 by Makidis Mixalis & Karakatsiotis Giorgos
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Mixalis & Karakatsiotis Giorgos 2004-2005
* ============================================================================
*/

// INCLUDE FILES
#include  <aknviewappui.h>
#include  <avkon.hrh>
#include  <AuebTriliza.rsg>
#include  "AuebTrilizaView.h"
#include  "AuebTrilizaContainer.h" 

// ================= MEMBER FUNCTIONS =======================

CAuebTrilizaView::CAuebTrilizaView(CAuebTrilizaAppUi* aUi, CAuebTrilizaDocument* aDocument)
: iUi(aUi), iDocument(aDocument)
{}

// ---------------------------------------------------------
// CAuebTrilizaView::ConstructL(const TRect& aRect)
// EPOC two-phased constructor
// ---------------------------------------------------------
//
void CAuebTrilizaView::ConstructL()
    {
    BaseConstructL( R_AUEBTRILIZA_VIEW1 );
    }

// ---------------------------------------------------------
// CAuebTrilizaView::~CAuebTrilizaView()
// ?implementation_description
// ---------------------------------------------------------
//
CAuebTrilizaView::~CAuebTrilizaView()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }

    delete iContainer;
    }

// ---------------------------------------------------------
// TUid CAuebTrilizaView::Id()
// ?implementation_description
// ---------------------------------------------------------
//
TUid CAuebTrilizaView::Id() const
    {
    return KViewId;
    }

// ---------------------------------------------------------
// CAuebTrilizaView::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CAuebTrilizaView::HandleCommandL(TInt aCommand)
    {   
    switch ( aCommand )
        {
        case EAknSoftkeyOk:
            {
            iEikonEnv->InfoMsg( _L("view1 ok") );
            break;
            }
        case EAknSoftkeyBack:
            {
            AppUi()->HandleCommandL(EEikCmdExit);
            break;
            }
        default:
            {
            AppUi()->HandleCommandL( aCommand );
            break;
            }
        }
    }

// ---------------------------------------------------------
// CAuebTrilizaView::HandleClientRectChange()
// ---------------------------------------------------------
//
void CAuebTrilizaView::HandleClientRectChange()
    {
    if ( iContainer )
        {
        iContainer->SetRect( ClientRect() );
        }
    }

// ---------------------------------------------------------
// CAuebTrilizaView::DoActivateL(...)
// ?implementation_description
// ---------------------------------------------------------
//
void CAuebTrilizaView::DoActivateL(
   const TVwsViewId& /*aPrevViewId*/,TUid /*aCustomMessageId*/,
   const TDesC8& /*aCustomMessage*/)
    {
    if (!iContainer)
        {
        iContainer = new (ELeave) CAuebTrilizaContainer(iUi, this);
        iContainer->SetMopParent(this);
        iContainer->ConstructL( ClientRect() );
        AppUi()->AddToStackL( *this, iContainer );
        }
	iUi->ShowDefaultNaviPaneL();
   }

// ---------------------------------------------------------
// CAuebTrilizaView::HandleCommandL(TInt aCommand)
// ?implementation_description
// ---------------------------------------------------------
//
void CAuebTrilizaView::DoDeactivate()
    {
    if ( iContainer )
        {
        AppUi()->RemoveFromViewStack( *this, iContainer );
        }
    
    delete iContainer;
    iContainer = NULL;
    }

// End of File

