/*
* ============================================================================
*  Name     : CAuebTrilizaApp from AuebTrilizaApp.cpp
*  Part of  : AuebTriliza
*  Created  : 11/12/2004 by Makidis Mixalis & Karakatsiotis Giorgos
*  Implementation notes:
*     Initial content was generated by Series 60 AppWizard.
*  Copyright: Makidis Mixalis & Karakatsiotis Giorgos 2004-2005
* ============================================================================
*/

// INCLUDE FILES
#include    "AuebTrilizaApp.h"
#include    "AuebTrilizaDocument.h"

// ================= MEMBER FUNCTIONS =======================

// ---------------------------------------------------------
// CAuebTrilizaApp::AppDllUid()
// Returns application UID
// ---------------------------------------------------------
//
TUid CAuebTrilizaApp::AppDllUid() const
    {
    return KUidAuebTriliza;
    }

   
// ---------------------------------------------------------
// CAuebTrilizaApp::CreateDocumentL()
// Creates CAuebTrilizaDocument object
// ---------------------------------------------------------
//
CApaDocument* CAuebTrilizaApp::CreateDocumentL()
    {
    return CAuebTrilizaDocument::NewL( *this );
    }

// ================= OTHER EXPORTED FUNCTIONS ==============
//
// ---------------------------------------------------------
// NewApplication() 
// Constructs CAuebTrilizaApp
// Returns: created application object
// ---------------------------------------------------------
//
EXPORT_C CApaApplication* NewApplication()
    {
    return new CAuebTrilizaApp;
    }

// ---------------------------------------------------------
// E32Dll(TDllReason) 
// Entry point function for EPOC Apps
// Returns: KErrNone: No error
// ---------------------------------------------------------
//
GLDEF_C TInt E32Dll( TDllReason )
    {
    return KErrNone;
    }

// End of File  

